# Generated by Django 5.2 on 2025-05-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='If you want to change your username, please [...]', max_length=100, unique=True),
        ),
    ]
