# Generated by Django 5.2 on 2025-04-09 18:03

import play2learn.storage_backends
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=play2learn.storage_backends.PublicMediaStorage(), upload_to='avatars/', validators=[users.models.validate_avatar]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
