# Generated by Django 5.2 on 2025-05-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateField(blank=True, help_text='If you fill your birthday wrong, please contact staff', null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='If you want to change your username, please [...]', max_length=100, unique=True, verbose_name='Username'),
        ),
    ]
