# Generated by Django 5.2 on 2025-04-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_avatar_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='anagramhunt_scores',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='mathfacts_scores',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
