# Generated by Django 5.2 on 2025-05-15 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_dob_alter_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='anagramhunt_review',
            new_name='anagramhunt_reviews',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='mathfacts_review',
            new_name='mathfacts_reviews',
        ),
    ]
