# Generated by Django 5.2 on 2025-04-08 21:49

import play2learn.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=play2learn.storage_backends.PublicMediaStorage(), upload_to='avatars/'),
        ),
    ]
