# Generated by Django 5.2 on 2025-04-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_anagramhunt_scores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_score_anagramhunt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_score_mathfacts',
            field=models.IntegerField(default=0),
        ),
    ]
