# Generated by Django 5.2.1 on 2025-06-18 21:33

import play2learn.storage_backends
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_anagramhunt_review_customuser_anagramhunt_reviews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Avatar cannot be larger than 200x200 pixels', null=True, storage=play2learn.storage_backends.PublicMediaStorage(), upload_to='avatars/', validators=[users.models.validate_avatar]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='Username'),
        ),
    ]
