# Generated by Django 5.2 on 2025-04-12 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_user_score_anagramhunt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_score_anagramhunt',
            new_name='score_anagramhunt',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='user_score_mathfacts',
            new_name='score_mathfacts',
        ),
    ]
