# Generated by Django 5.2 on 2025-04-12 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_user_score_anagramhunt_customuser_score_anagramhunt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='score_anagramhunt',
            new_name='anagramhunt_score',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='score_mathfacts',
            new_name='mathfacts_score',
        ),
    ]
