# Generated by Django 5.2 on 2025-04-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_score_anagramhunt_customuser_anagramhunt_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='anagramhunt_review',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mathfacts_review',
            field=models.TextField(blank=True, default=None),
        ),
    ]
