# Generated by Django 5.2 on 2025-04-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_anagramhunt_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='anagramhunt_review',
            field=models.TextField(blank=True, null=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mathfacts_review',
            field=models.TextField(blank=True, null=None),
        ),
    ]
