# Generated by Django 5.2 on 2025-05-12 18:24

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('scoreboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagramhuntscoreboard',
            name='time_left',
            field=models.DurationField(default=datetime.timedelta(seconds=0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anagramhuntscoreboard',
            name='word_length',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mathfactsscoreboard',
            name='max_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mathfactsscoreboard',
            name='operation',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mathfactsscoreboard',
            name='time_left',
            field=models.DurationField(default=datetime.timedelta(seconds=0)),
            preserve_default=False,
        ),
    ]
