# Generated by Django 5.2 on 2025-05-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboards', '0003_alter_mathfactsscoreboard_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathfactsscoreboard',
            name='max_number',
            field=models.IntegerField(max_length=20),
        ),
    ]
