# Generated by Django 5.2 on 2025-05-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboards', '0004_alter_mathfactsscoreboard_max_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathfactsscoreboard',
            name='max_number',
            field=models.IntegerField(),
        ),
    ]
