# Generated by Django 5.2 on 2025-05-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboards', '0007_anagramhuntuserscores_mathfactsuserscores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathfactsuserscores',
            name='operation',
            field=models.CharField(max_length=100),
        ),
    ]
