# Generated by Django 5.2 on 2025-05-13 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagramhuntscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_anagram_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mathfactsscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_math_scores', to=settings.AUTH_USER_MODEL),
        ),
    ]
